# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure App Services

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_PACKAGE_PATH: .
      AZURE_WEBAPP_NAME: Vacations
      WORKING_PATH: ./src/Maa.Vacations.WebApi
      APP_PATH: ./src/Maa.Vacations.WebApi/app

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        # Documentation: https://github.com/actions/setup-dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
          include-prerelease: false

      - name: Build
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet build --configuration Release

      - name: Publish
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet publish --no-restore -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/app

      - name: Install EF Migrations
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet tool install --global dotnet-ef

      - name: Run Migrations
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet ef database update

      - name: Move Migrations Database
        working-directory: ${{env.WORKING_PATH}}
        run: mv Vacations.sqllitedb ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/app/

      # - name: Run Migrations
      #   working-directory: ${{env.WORKING_PATH}}
      #   run: |
      #     dotnet ef database update
      #     mv Vacations.sqllitedb ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/app/

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          slot-name: "production"
          publish-profile: ${{secrets.AZURE_APP_SERVICES_WEB_APP}}
          package: ${{env.APP_PATH}}
