# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure App Services

on:
  push:
    branches:
      - add-github-action-deployment

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_PACKAGE_PATH: .
      AZURE_WEBAPP_NAME: Vacations
      WORKING_PATH: ./src/Maa.Vacations.WebApi
      APP_PATH: ./src/Maa.Vacations.WebApi/app

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
          include-prerelease: false

      - name: Building
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet build --configuration Release

      - name: Publishing
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet publish --no-restore -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/app

      - name: Installing EF Migrations
        working-directory: ${{env.WORKING_PATH}}
        run: dotnet tool install --global dotnet-ef

      - name: run migrations
        working-directory: ${{env.APP_PATH}}
        run: dotnet ef database update

      # - name: depoyment
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{env.AZURE_WEBAPP_NAME}}
      #     slot-name: "production"
      #     # path: ${{github.workspace}}
      #     publish-profile: ${{secrets.AZURE_APP_SERVICES_WEB_APP}}
      #     package: ${{env.APP_PATH}}
